// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AccessPermissionV1 - A permission governing access to a resource.
type AccessPermissionV1 struct {
	// The resources included with this permission.
	Resources []PermissionResourceV1 `json:"resources"`
	// The id of the role that applies to this permission.
	RoleID string `json:"roleId"`
	// The name of the role that applies to this permission.
	RoleName string `json:"roleName"`
}
