// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddPermissionsToUserV1Output - Returns the user's permissions, including the added permissions.
type AddPermissionsToUserV1Output struct {
	// The new permissions.
	Permissions []AccessPermissionV1 `json:"permissions"`
}
