// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddUsersToUserGroupV1Input - Adds a list of users and invites to a user group.
type AddUsersToUserGroupV1Input struct {
	// The email addresses of the users and invites to add.
	Emails []string `json:"emails"`
}
