// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateInvitesV1Input - Invites a user to a Workspace with specified permissions.
type CreateInvitesV1Input struct {
	// The list of invites.
	Invites []InviteV1 `json:"invites"`
}
