// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateSourceV1OutputLogosBeta - Represents a logo.
type CreateSourceV1OutputLogosBeta struct {
	// The alternative text for this logo.
	Alt *string `json:"alt,omitempty"`
	// The default URL for this logo.
	Default string `json:"default"`
	// The logo mark.
	Mark *string `json:"mark,omitempty"`
}

func (o *CreateSourceV1OutputLogosBeta) GetAlt() *string {
	if o == nil {
		return nil
	}
	return o.Alt
}

func (o *CreateSourceV1OutputLogosBeta) GetDefault() string {
	if o == nil {
		return ""
	}
	return o.Default
}

func (o *CreateSourceV1OutputLogosBeta) GetMark() *string {
	if o == nil {
		return nil
	}
	return o.Mark
}

// CreateSourceV1OutputSourceMetadataV1 - A website, server library, mobile SDK, or cloud application which can send data into Segment.
type CreateSourceV1OutputSourceMetadataV1 struct {
	// A list of categories this Source belongs to.
	Categories []string `json:"categories"`
	// The description of this Source.
	Description string `json:"description"`
	// The id for this Source metadata in the Segment catalog.
	//
	// Config API note: analogous to `name`.
	ID string `json:"id"`
	// True if this is a Cloud Event Source.
	IsCloudEventSource bool `json:"isCloudEventSource"`
	// The logos for this Source.
	Logos CreateSourceV1OutputLogosBeta `json:"logos"`
	// The user-friendly name of this Source.
	//
	// Config API note: equal to `displayName`.
	Name string `json:"name"`
	// Options for this Source.
	Options []IntegrationOptionBeta `json:"options"`
	// The slug that identifies this Source in the Segment app.
	//
	// Config API note: equal to `name`.
	Slug string `json:"slug"`
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetCategories() []string {
	if o == nil {
		return []string{}
	}
	return o.Categories
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetIsCloudEventSource() bool {
	if o == nil {
		return false
	}
	return o.IsCloudEventSource
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetLogos() CreateSourceV1OutputLogosBeta {
	if o == nil {
		return CreateSourceV1OutputLogosBeta{}
	}
	return o.Logos
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetOptions() []IntegrationOptionBeta {
	if o == nil {
		return []IntegrationOptionBeta{}
	}
	return o.Options
}

func (o *CreateSourceV1OutputSourceMetadataV1) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// CreateSourceV1OutputSourceV1 - Defines a data Source for Segment data.
type CreateSourceV1OutputSourceV1 struct {
	// Enable to receive data from the Source.
	Enabled bool `json:"enabled"`
	// The id of the Source.
	//
	// Config API note: analogous to `name`.
	ID string `json:"id"`
	// A list of labels applied to the Source.
	Labels []LabelV1 `json:"labels"`
	// The metadata for the Source.
	//
	// Config API note: includes `catalogName` and `catalogId`.
	Metadata CreateSourceV1OutputSourceMetadataV1 `json:"metadata"`
	// The name of the Source.
	//
	// Config API note: equal to `displayName`.
	Name *string `json:"name,omitempty"`
	// The settings associated with the Source.
	Settings map[string]interface{} `json:"settings,omitempty"`
	// The slug used to identify the Source in the Segment app.
	//
	// Config API note: equal to `name`.
	Slug string `json:"slug"`
	// The id of the Workspace that owns the Source.
	//
	// Config API note: equal to `parent`.
	WorkspaceID string `json:"workspaceId"`
	// The write keys used to send data from the Source. This field is left empty when the current token does not have the
	// 'source admin' permission.
	WriteKeys []string `json:"writeKeys"`
}

func (o *CreateSourceV1OutputSourceV1) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *CreateSourceV1OutputSourceV1) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateSourceV1OutputSourceV1) GetLabels() []LabelV1 {
	if o == nil {
		return []LabelV1{}
	}
	return o.Labels
}

func (o *CreateSourceV1OutputSourceV1) GetMetadata() CreateSourceV1OutputSourceMetadataV1 {
	if o == nil {
		return CreateSourceV1OutputSourceMetadataV1{}
	}
	return o.Metadata
}

func (o *CreateSourceV1OutputSourceV1) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateSourceV1OutputSourceV1) GetSettings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Settings
}

func (o *CreateSourceV1OutputSourceV1) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *CreateSourceV1OutputSourceV1) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *CreateSourceV1OutputSourceV1) GetWriteKeys() []string {
	if o == nil {
		return []string{}
	}
	return o.WriteKeys
}

// CreateSourceV1Output - Returns a newly created Source.
type CreateSourceV1Output struct {
	// The newly created Source.
	Source CreateSourceV1OutputSourceV1 `json:"source"`
}

func (o *CreateSourceV1Output) GetSource() CreateSourceV1OutputSourceV1 {
	if o == nil {
		return CreateSourceV1OutputSourceV1{}
	}
	return o.Source
}
