// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CreateSourceAlphaOutputLogosBeta - Represents a logo.
type CreateSourceAlphaOutputLogosBeta struct {
	// The alternative text for this logo.
	Alt *string `json:"alt,omitempty"`
	// The default URL for this logo.
	Default string `json:"default"`
	// The logo mark.
	Mark *string `json:"mark,omitempty"`
}

func (o *CreateSourceAlphaOutputLogosBeta) GetAlt() *string {
	if o == nil {
		return nil
	}
	return o.Alt
}

func (o *CreateSourceAlphaOutputLogosBeta) GetDefault() string {
	if o == nil {
		return ""
	}
	return o.Default
}

func (o *CreateSourceAlphaOutputLogosBeta) GetMark() *string {
	if o == nil {
		return nil
	}
	return o.Mark
}

// CreateSourceAlphaOutputSourceMetadataV1 - A website, server library, mobile SDK, or cloud application which can send data into Segment.
type CreateSourceAlphaOutputSourceMetadataV1 struct {
	// A list of categories this Source belongs to.
	Categories []string `json:"categories"`
	// The description of this Source.
	Description string `json:"description"`
	// The id for this Source metadata in the Segment catalog.
	//
	// Config API note: analogous to `name`.
	ID string `json:"id"`
	// True if this is a Cloud Event Source.
	IsCloudEventSource bool `json:"isCloudEventSource"`
	// The logos for this Source.
	Logos CreateSourceAlphaOutputLogosBeta `json:"logos"`
	// The user-friendly name of this Source.
	//
	// Config API note: equal to `displayName`.
	Name string `json:"name"`
	// Options for this Source.
	Options []IntegrationOptionBeta `json:"options"`
	// The slug that identifies this Source in the Segment app.
	//
	// Config API note: equal to `name`.
	Slug string `json:"slug"`
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetCategories() []string {
	if o == nil {
		return []string{}
	}
	return o.Categories
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetIsCloudEventSource() bool {
	if o == nil {
		return false
	}
	return o.IsCloudEventSource
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetLogos() CreateSourceAlphaOutputLogosBeta {
	if o == nil {
		return CreateSourceAlphaOutputLogosBeta{}
	}
	return o.Logos
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetOptions() []IntegrationOptionBeta {
	if o == nil {
		return []IntegrationOptionBeta{}
	}
	return o.Options
}

func (o *CreateSourceAlphaOutputSourceMetadataV1) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// CreateSourceAlphaOutputSourceAlpha - Defines a data Source for Segment data.
type CreateSourceAlphaOutputSourceAlpha struct {
	// Enable to receive data from the Source.
	Enabled bool `json:"enabled"`
	// The id of the Source.
	//
	// Config API note: analogous to `name`.
	ID string `json:"id"`
	// A list of labels applied to the Source.
	Labels []LabelV1 `json:"labels"`
	// The metadata for the Source.
	//
	// Config API note: includes `catalogName` and `catalogId`.
	Metadata CreateSourceAlphaOutputSourceMetadataV1 `json:"metadata"`
	// The name of the Source.
	//
	// Config API note: equal to `displayName`.
	Name *string `json:"name,omitempty"`
	// The settings associated with the Source.
	Settings map[string]interface{} `json:"settings,omitempty"`
	// The slug used to identify the Source in the Segment app.
	//
	// Config API note: equal to `name`.
	Slug string `json:"slug"`
	// The id of the Workspace that owns the Source.
	//
	// Config API note: equal to `parent`.
	WorkspaceID string `json:"workspaceId"`
	// The write keys used to send data from the Source. This field is left empty when the current token does not have the
	// 'source admin' permission.
	WriteKeys []string `json:"writeKeys"`
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetEnabled() bool {
	if o == nil {
		return false
	}
	return o.Enabled
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetLabels() []LabelV1 {
	if o == nil {
		return []LabelV1{}
	}
	return o.Labels
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetMetadata() CreateSourceAlphaOutputSourceMetadataV1 {
	if o == nil {
		return CreateSourceAlphaOutputSourceMetadataV1{}
	}
	return o.Metadata
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetSettings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Settings
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *CreateSourceAlphaOutputSourceAlpha) GetWriteKeys() []string {
	if o == nil {
		return []string{}
	}
	return o.WriteKeys
}

// CreateSourceAlphaOutput - Returns the newly Source.
type CreateSourceAlphaOutput struct {
	// The newly created Source.
	Source CreateSourceAlphaOutputSourceAlpha `json:"source"`
}

func (o *CreateSourceAlphaOutput) GetSource() CreateSourceAlphaOutputSourceAlpha {
	if o == nil {
		return CreateSourceAlphaOutputSourceAlpha{}
	}
	return o.Source
}
