// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// DestinationMetadataComponentV1Owner - The owner of this component. Either 'SEGMENT' or 'PARTNER'.
type DestinationMetadataComponentV1Owner string

const (
	DestinationMetadataComponentV1OwnerPartner DestinationMetadataComponentV1Owner = "PARTNER"
	DestinationMetadataComponentV1OwnerSegment DestinationMetadataComponentV1Owner = "SEGMENT"
)

func (e DestinationMetadataComponentV1Owner) ToPointer() *DestinationMetadataComponentV1Owner {
	return &e
}

func (e *DestinationMetadataComponentV1Owner) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PARTNER":
		fallthrough
	case "SEGMENT":
		*e = DestinationMetadataComponentV1Owner(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationMetadataComponentV1Owner: %v", v)
	}
}

// DestinationMetadataComponentV1Type - The component type.
type DestinationMetadataComponentV1Type string

const (
	DestinationMetadataComponentV1TypeAndroid DestinationMetadataComponentV1Type = "ANDROID"
	DestinationMetadataComponentV1TypeBrowser DestinationMetadataComponentV1Type = "BROWSER"
	DestinationMetadataComponentV1TypeIos     DestinationMetadataComponentV1Type = "IOS"
	DestinationMetadataComponentV1TypeServer  DestinationMetadataComponentV1Type = "SERVER"
)

func (e DestinationMetadataComponentV1Type) ToPointer() *DestinationMetadataComponentV1Type {
	return &e
}

func (e *DestinationMetadataComponentV1Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ANDROID":
		fallthrough
	case "BROWSER":
		fallthrough
	case "IOS":
		fallthrough
	case "SERVER":
		*e = DestinationMetadataComponentV1Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DestinationMetadataComponentV1Type: %v", v)
	}
}

// DestinationMetadataComponentV1 - Represents a component this Destination provides.
type DestinationMetadataComponentV1 struct {
	// Link to the repository hosting the code for this component.
	Code string `json:"code"`
	// The owner of this component. Either 'SEGMENT' or 'PARTNER'.
	Owner *DestinationMetadataComponentV1Owner `json:"owner,omitempty"`
	// The component type.
	Type DestinationMetadataComponentV1Type `json:"type"`
}
