// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// GetFunctionV1OutputResourceType - The Function type.
//
// Config API note: equal to `type`.
type GetFunctionV1OutputResourceType string

const (
	GetFunctionV1OutputResourceTypeDestination       GetFunctionV1OutputResourceType = "DESTINATION"
	GetFunctionV1OutputResourceTypeInsertDestination GetFunctionV1OutputResourceType = "INSERT_DESTINATION"
	GetFunctionV1OutputResourceTypeSource            GetFunctionV1OutputResourceType = "SOURCE"
)

func (e GetFunctionV1OutputResourceType) ToPointer() *GetFunctionV1OutputResourceType {
	return &e
}

func (e *GetFunctionV1OutputResourceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DESTINATION":
		fallthrough
	case "INSERT_DESTINATION":
		fallthrough
	case "SOURCE":
		*e = GetFunctionV1OutputResourceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetFunctionV1OutputResourceType: %v", v)
	}
}

// GetFunctionV1OutputFunction - A Function object.
type GetFunctionV1OutputFunction struct {
	// The max count of the batch for this Function.
	BatchMaxCount *float64 `json:"batchMaxCount,omitempty"`
	// The catalog id of this Function.
	CatalogID *string `json:"catalogId,omitempty"`
	// The Function code.
	Code *string `json:"code,omitempty"`
	// The time this Function was created.
	CreatedAt *string `json:"createdAt,omitempty"`
	// The id of the user who created this Function.
	CreatedBy *string `json:"createdBy,omitempty"`
	// The time of this Function's last deployment.
	DeployedAt *string `json:"deployedAt,omitempty"`
	// A description for this Function.
	Description *string `json:"description,omitempty"`
	// A display name for this Function.
	DisplayName *string `json:"displayName,omitempty"`
	// An identifier for this Function.
	ID *string `json:"id,omitempty"`
	// Whether the deployment of this Function is the latest version.
	IsLatestVersion *bool `json:"isLatestVersion,omitempty"`
	// The URL of the logo for this Function.
	LogoURL *string `json:"logoUrl,omitempty"`
	// The preview webhook URL for this Function.
	PreviewWebhookURL *string `json:"previewWebhookUrl,omitempty"`
	// The Function type.
	//
	// Config API note: equal to `type`.
	ResourceType *GetFunctionV1OutputResourceType `json:"resourceType,omitempty"`
	// The list of settings for this Function.
	Settings []FunctionSettingV1 `json:"settings,omitempty"`
}

func (o *GetFunctionV1OutputFunction) GetBatchMaxCount() *float64 {
	if o == nil {
		return nil
	}
	return o.BatchMaxCount
}

func (o *GetFunctionV1OutputFunction) GetCatalogID() *string {
	if o == nil {
		return nil
	}
	return o.CatalogID
}

func (o *GetFunctionV1OutputFunction) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *GetFunctionV1OutputFunction) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetFunctionV1OutputFunction) GetCreatedBy() *string {
	if o == nil {
		return nil
	}
	return o.CreatedBy
}

func (o *GetFunctionV1OutputFunction) GetDeployedAt() *string {
	if o == nil {
		return nil
	}
	return o.DeployedAt
}

func (o *GetFunctionV1OutputFunction) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *GetFunctionV1OutputFunction) GetDisplayName() *string {
	if o == nil {
		return nil
	}
	return o.DisplayName
}

func (o *GetFunctionV1OutputFunction) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *GetFunctionV1OutputFunction) GetIsLatestVersion() *bool {
	if o == nil {
		return nil
	}
	return o.IsLatestVersion
}

func (o *GetFunctionV1OutputFunction) GetLogoURL() *string {
	if o == nil {
		return nil
	}
	return o.LogoURL
}

func (o *GetFunctionV1OutputFunction) GetPreviewWebhookURL() *string {
	if o == nil {
		return nil
	}
	return o.PreviewWebhookURL
}

func (o *GetFunctionV1OutputFunction) GetResourceType() *GetFunctionV1OutputResourceType {
	if o == nil {
		return nil
	}
	return o.ResourceType
}

func (o *GetFunctionV1OutputFunction) GetSettings() []FunctionSettingV1 {
	if o == nil {
		return nil
	}
	return o.Settings
}

// GetFunctionV1Output - Gets a single Function.
type GetFunctionV1Output struct {
	// A Function object.
	Function *GetFunctionV1OutputFunction `json:"function"`
}

func (o *GetFunctionV1Output) GetFunction() *GetFunctionV1OutputFunction {
	if o == nil {
		return nil
	}
	return o.Function
}
