// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions - The latest version of Edge Function bundle.
type GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions struct {
	// Creation date.
	CreatedAt string `json:"createdAt"`
	// Creating user's id.
	CreatedBy string `json:"createdBy"`
	// The CDN URL that can be used to fetch your latest EdgeFunctions bundle.
	DownloadURL string `json:"downloadURL"`
	// The Edge Function id.
	ID string `json:"id"`
	// The Source id.
	SourceID string `json:"sourceId"`
	// Revision number associated with the latest Edge Function.
	Version float64 `json:"version"`
}

func (o *GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions) GetCreatedAt() string {
	if o == nil {
		return ""
	}
	return o.CreatedAt
}

func (o *GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions) GetCreatedBy() string {
	if o == nil {
		return ""
	}
	return o.CreatedBy
}

func (o *GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions) GetDownloadURL() string {
	if o == nil {
		return ""
	}
	return o.DownloadURL
}

func (o *GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

func (o *GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions) GetVersion() float64 {
	if o == nil {
		return 0.0
	}
	return o.Version
}

// GetLatestFromEdgeFunctionsAlphaOutput - Output for GetLatestFromEdgeFunctions.
type GetLatestFromEdgeFunctionsAlphaOutput struct {
	// The latest version of Edge Function bundle.
	EdgeFunctions GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions `json:"edgeFunctions"`
}

func (o *GetLatestFromEdgeFunctionsAlphaOutput) GetEdgeFunctions() GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions {
	if o == nil {
		return GetLatestFromEdgeFunctionsAlphaOutputEdgeFunctions{}
	}
	return o.EdgeFunctions
}
