// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetSourcesCatalogV1OutputPaginationOutput - Pagination metadata for a list response.
//
// Responses return this object alongside a list of resources, which provides the necessary metadata for manipulating a
// paginated collection. In operations that return lists, it's always present, though some of its fields might not be.
type GetSourcesCatalogV1OutputPaginationOutput struct {
	// The current cursor within a collection.
	//
	// Consumers of the API must treat this value as opaque.
	Current string `json:"current"`
	// A pointer to the next page.
	//
	// This does not return when you retrieve the last page.
	//
	// Consumers of the API must treat this value as opaque.
	Next *string `json:"next,omitempty"`
	// A pointer to the previous page.
	//
	// This does not return when you retrieve the first page.
	//
	// Consumers of the API must treat this value as opaque.
	Previous *string `json:"previous,omitempty"`
	// The total number of entries available in the collection.
	//
	// If calculating it impacts performance, the response may omit this field.
	TotalEntries *float64 `json:"totalEntries,omitempty"`
}

func (o *GetSourcesCatalogV1OutputPaginationOutput) GetCurrent() string {
	if o == nil {
		return ""
	}
	return o.Current
}

func (o *GetSourcesCatalogV1OutputPaginationOutput) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *GetSourcesCatalogV1OutputPaginationOutput) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *GetSourcesCatalogV1OutputPaginationOutput) GetTotalEntries() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalEntries
}

// GetSourcesCatalogV1Output - Returns a list of all Source catalog items contained within a given page.
type GetSourcesCatalogV1Output struct {
	// Information about the pagination of this response.
	Pagination GetSourcesCatalogV1OutputPaginationOutput `json:"pagination"`
	// All Source catalog items contained within the requested page.
	SourcesCatalog []SourceMetadataV1 `json:"sourcesCatalog"`
}

func (o *GetSourcesCatalogV1Output) GetPagination() GetSourcesCatalogV1OutputPaginationOutput {
	if o == nil {
		return GetSourcesCatalogV1OutputPaginationOutput{}
	}
	return o.Pagination
}

func (o *GetSourcesCatalogV1Output) GetSourcesCatalog() []SourceMetadataV1 {
	if o == nil {
		return []SourceMetadataV1{}
	}
	return o.SourcesCatalog
}
