// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GetWorkspaceV1OutputWorkspaceV1 - An organized group of Sources and Destinations managed by a team.
type GetWorkspaceV1OutputWorkspaceV1 struct {
	// The unique identifier.
	ID string `json:"id"`
	// The human-readable name.
	Name string `json:"name"`
	// The URL-friendly slug.
	Slug string `json:"slug"`
}

func (o *GetWorkspaceV1OutputWorkspaceV1) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetWorkspaceV1OutputWorkspaceV1) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GetWorkspaceV1OutputWorkspaceV1) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

// GetWorkspaceV1Output - Represents the output of loading the Workspace.
type GetWorkspaceV1Output struct {
	// The Workspace.
	Workspace GetWorkspaceV1OutputWorkspaceV1 `json:"workspace"`
}

func (o *GetWorkspaceV1Output) GetWorkspace() GetWorkspaceV1OutputWorkspaceV1 {
	if o == nil {
		return GetWorkspaceV1OutputWorkspaceV1{}
	}
	return o.Workspace
}
