// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// InvitePermissionV1 - Defines a permission to apply to the user in an invite.
type InvitePermissionV1 struct {
	// The labels that determine which resources to grant users access to.
	Labels []AllowedLabelBeta `json:"labels,omitempty"`
	// The resources to grant the invited users access to.
	Resources []ResourceV1 `json:"resources,omitempty"`
	// The id of the role.
	RoleID string `json:"roleId"`
}

func (o *InvitePermissionV1) GetLabels() []AllowedLabelBeta {
	if o == nil {
		return nil
	}
	return o.Labels
}

func (o *InvitePermissionV1) GetResources() []ResourceV1 {
	if o == nil {
		return nil
	}
	return o.Resources
}

func (o *InvitePermissionV1) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}
