// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListLabelsV1Output - Returns all available labels for the current Workspace.
type ListLabelsV1Output struct {
	// All labels associated with the current Workspace.
	Labels []LabelV1 `json:"labels"`
}
