// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListReverseEtlModelsOutputPaginationOutput - Pagination metadata for a list response.
//
// Responses return this object alongside a list of resources, which provides the necessary metadata for manipulating a
// paginated collection. In operations that return lists, it's always present, though some of its fields might not be.
type ListReverseEtlModelsOutputPaginationOutput struct {
	// The current cursor within a collection.
	//
	// Consumers of the API must treat this value as opaque.
	Current string `json:"current"`
	// A pointer to the next page.
	//
	// This does not return when you retrieve the last page.
	//
	// Consumers of the API must treat this value as opaque.
	Next *string `json:"next,omitempty"`
	// A pointer to the previous page.
	//
	// This does not return when you retrieve the first page.
	//
	// Consumers of the API must treat this value as opaque.
	Previous *string `json:"previous,omitempty"`
	// The total number of entries available in the collection.
	//
	// If calculating it impacts performance, the response may omit this field.
	TotalEntries *float64 `json:"totalEntries,omitempty"`
}

func (o *ListReverseEtlModelsOutputPaginationOutput) GetCurrent() string {
	if o == nil {
		return ""
	}
	return o.Current
}

func (o *ListReverseEtlModelsOutputPaginationOutput) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListReverseEtlModelsOutputPaginationOutput) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListReverseEtlModelsOutputPaginationOutput) GetTotalEntries() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalEntries
}

// ListReverseEtlModelsOutput - Defines the result of listing Models.
type ListReverseEtlModelsOutput struct {
	// A list of Models that belong to the Workspace.
	Models []ReverseEtlModel `json:"models"`
	// Information about the pagination of this response.
	Pagination ListReverseEtlModelsOutputPaginationOutput `json:"pagination"`
}

func (o *ListReverseEtlModelsOutput) GetModels() []ReverseEtlModel {
	if o == nil {
		return []ReverseEtlModel{}
	}
	return o.Models
}

func (o *ListReverseEtlModelsOutput) GetPagination() ListReverseEtlModelsOutputPaginationOutput {
	if o == nil {
		return ListReverseEtlModelsOutputPaginationOutput{}
	}
	return o.Pagination
}
