// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Result - The filtered JSON output.
type Result struct {
}

// PreviewDestinationFilterV1Output - Preview output from applying the Destination filter.
// Segment modifies or nullifies payloads depending on the provided filter actions.
type PreviewDestinationFilterV1Output struct {
	// The pre-filter JSON input.
	InputPayload map[string]interface{} `json:"inputPayload"`
	// The filtered JSON output.
	Result *Result `json:"result"`
}

func (o *PreviewDestinationFilterV1Output) GetInputPayload() map[string]interface{} {
	if o == nil {
		return map[string]interface{}{}
	}
	return o.InputPayload
}

func (o *PreviewDestinationFilterV1Output) GetResult() *Result {
	if o == nil {
		return nil
	}
	return o.Result
}
