// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ReplacePermissionsForUserV1Output - Returns the user's permissions, including the updated permissions.
type ReplacePermissionsForUserV1Output struct {
	// The updated permissions.
	Permissions []AccessPermissionV1 `json:"permissions"`
}
