// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ReplacePermissionsForUserGroupV1Output - Returns the user group's permissions, including the updated permissions.
type ReplacePermissionsForUserGroupV1Output struct {
	// The updated permissions.
	Permissions []AccessPermissionV1 `json:"permissions"`
}

func (o *ReplacePermissionsForUserGroupV1Output) GetPermissions() []AccessPermissionV1 {
	if o == nil {
		return []AccessPermissionV1{}
	}
	return o.Permissions
}
