// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ReplaceLabelsInSourceV1Input - Replaces all labels in a Source with a list of new labels.
type ReplaceLabelsInSourceV1Input struct {
	// The list of labels to replace in the Source.
	Labels []LabelV1 `json:"labels"`
}

func (o *ReplaceLabelsInSourceV1Input) GetLabels() []LabelV1 {
	if o == nil {
		return []LabelV1{}
	}
	return o.Labels
}
