// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ReplacePermissionsForUserGroupV1Input - Updates the list of permissions for a user group.
type ReplacePermissionsForUserGroupV1Input struct {
	// The permissions to replace with.
	Permissions []PermissionInputV1 `json:"permissions"`
}
