// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateSubscriptionForDestinationAlphaOutputDestinationSubscription - The Destination subscription.
type UpdateSubscriptionForDestinationAlphaOutputDestinationSubscription struct {
	// The unique identifier for the Destination action to trigger.
	ActionID string `json:"actionId"`
	// The URL-friendly key for the associated Destination action.
	ActionSlug string `json:"actionSlug"`
	// The associated Destination instance id.
	DestinationID string `json:"destinationId"`
	// Is the subscription enabled.
	Enabled bool `json:"enabled"`
	// The unique identifier for the subscription.
	ID string `json:"id"`
	// The unique identifier for the linked ReverseETLModel, if this part of a
	// Reverse ETL connection.
	ModelID *string `json:"modelId,omitempty"`
	// The name of the subscription.
	Name string `json:"name"`
	// The customer settings for action fields.
	Settings map[string]interface{} `json:"settings"`
	// FQL string that describes what events should trigger a Destination action.
	Trigger string `json:"trigger"`
}

// UpdateSubscriptionForDestinationAlphaOutput - Returns the updated Destination subscription.
type UpdateSubscriptionForDestinationAlphaOutput struct {
	// The Destination subscription.
	Subscription UpdateSubscriptionForDestinationAlphaOutputDestinationSubscription `json:"subscription"`
}
