// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UpdateProfilesWarehouseForSpaceWarehouseAlphaInput - Updates a Profiles Warehouse based on a set of parameters.
type UpdateProfilesWarehouseForSpaceWarehouseAlphaInput struct {
	// Enable to allow this Warehouse to receive data. Defaults to true.
	Enabled *bool `json:"enabled,omitempty"`
	// An optional human-readable name for this Warehouse.
	Name *string `json:"name,omitempty"`
	// The custom schema name that Segment uses on the Warehouse side. The space slug value is default otherwise.
	SchemaName *string `json:"schemaName,omitempty"`
	// A key-value object that contains instance-specific settings for a Warehouse.
	//
	// Different kinds of Warehouses require different settings. The required and optional settings
	// for a Warehouse are described in the `options` object of the associated Warehouse metadata.
	//
	// You can find the full list of Warehouse metadata and related settings information in the
	// `/catalog/warehouses` endpoint.
	Settings map[string]interface{} `json:"settings"`
}

func (o *UpdateProfilesWarehouseForSpaceWarehouseAlphaInput) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *UpdateProfilesWarehouseForSpaceWarehouseAlphaInput) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UpdateProfilesWarehouseForSpaceWarehouseAlphaInput) GetSchemaName() *string {
	if o == nil {
		return nil
	}
	return o.SchemaName
}

func (o *UpdateProfilesWarehouseForSpaceWarehouseAlphaInput) GetSettings() map[string]interface{} {
	if o == nil {
		return map[string]interface{}{}
	}
	return o.Settings
}
