// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WarehouseMetadataV1LogosBeta - Represents a logo.
type WarehouseMetadataV1LogosBeta struct {
	// The alternative text for this logo.
	Alt *string `json:"alt,omitempty"`
	// The default URL for this logo.
	Default string `json:"default"`
	// The logo mark.
	Mark *string `json:"mark,omitempty"`
}

// WarehouseMetadataV1 - The metadata for an instance of Segment’s data Warehouse product.
type WarehouseMetadataV1 struct {
	// A description, in English, of this object.
	Description string `json:"description"`
	// The id of this object.
	ID string `json:"id"`
	// Logo information for this object.
	Logos WarehouseMetadataV1LogosBeta `json:"logos"`
	// The name of this object.
	Name string `json:"name"`
	// The Integration options for this object.
	Options []IntegrationOptionBeta `json:"options"`
	// A human-readable, unique identifier for object.
	Slug string `json:"slug"`
}
