// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// AddLabelsToSourceAlphaOutput - Applies an existing label to an existing Source.
type AddLabelsToSourceAlphaOutput struct {
	// All labels applied to the Source.
	Labels []LabelAlpha `json:"labels"`
}

func (o *AddLabelsToSourceAlphaOutput) GetLabels() []LabelAlpha {
	if o == nil {
		return []LabelAlpha{}
	}
	return o.Labels
}
