// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListRolesV1OutputPagination - Information about the pagination of this response.
type ListRolesV1OutputPagination struct {
	// The current cursor within a collection.
	//
	// Consumers of the API must treat this value as opaque.
	Current string `json:"current"`
	// A pointer to the next page.
	//
	// This does not return when you retrieve the last page.
	//
	// Consumers of the API must treat this value as opaque.
	Next *string `json:"next,omitempty"`
	// A pointer to the previous page.
	//
	// This does not return when you retrieve the first page.
	//
	// Consumers of the API must treat this value as opaque.
	Previous *string `json:"previous,omitempty"`
	// The total number of entries available in the collection.
	//
	// If calculating it impacts performance, the response may omit this field.
	TotalEntries *float64 `json:"totalEntries,omitempty"`
}

func (o *ListRolesV1OutputPagination) GetCurrent() string {
	if o == nil {
		return ""
	}
	return o.Current
}

func (o *ListRolesV1OutputPagination) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *ListRolesV1OutputPagination) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

func (o *ListRolesV1OutputPagination) GetTotalEntries() *float64 {
	if o == nil {
		return nil
	}
	return o.TotalEntries
}

// ListRolesV1Output - Returns the list of roles.
type ListRolesV1Output struct {
	// Information about the pagination of this response.
	Pagination ListRolesV1OutputPagination `json:"pagination"`
	// The list of roles.
	Roles []RoleV1 `json:"roles"`
}

func (o *ListRolesV1Output) GetPagination() ListRolesV1OutputPagination {
	if o == nil {
		return ListRolesV1OutputPagination{}
	}
	return o.Pagination
}

func (o *ListRolesV1Output) GetRoles() []RoleV1 {
	if o == nil {
		return []RoleV1{}
	}
	return o.Roles
}
