// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Input - A set of valid Destination input params required for updating.
type Input struct {
	// Is the subscription enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// The user-defined name for the subscription.
	Name *string `json:"name,omitempty"`
	// The fields used for configuring this action.
	Settings map[string]interface{} `json:"settings,omitempty"`
	// The fql statement.
	Trigger *string `json:"trigger,omitempty"`
}

func (o *Input) GetEnabled() *bool {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *Input) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Input) GetSettings() map[string]interface{} {
	if o == nil {
		return nil
	}
	return o.Settings
}

func (o *Input) GetTrigger() *string {
	if o == nil {
		return nil
	}
	return o.Trigger
}

// UpdateSubscriptionForDestinationAlphaInput - The basic input parameters for updating a Destination subscription.
type UpdateSubscriptionForDestinationAlphaInput struct {
	// A set of valid Destination input params required for updating.
	Input Input `json:"input"`
}

func (o *UpdateSubscriptionForDestinationAlphaInput) GetInput() Input {
	if o == nil {
		return Input{}
	}
	return o.Input
}
