// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type CreateEdgeFunctionsRequest struct {
	CreateEdgeFunctionsAlphaInput shared.CreateEdgeFunctionsAlphaInput `request:"mediaType=application/vnd.segment.v1alpha+json"`
	SourceID                      string                               `pathParam:"style=simple,explode=false,name=sourceId"`
}

// CreateEdgeFunctions200ApplicationVndSegmentV1alphaPlusJSON - OK
type CreateEdgeFunctions200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Output for CreateEdgeFunctions.
	Data *shared.CreateEdgeFunctionsAlphaOutput `json:"data,omitempty"`
}

type CreateEdgeFunctionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// OK
	CreateEdgeFunctions200ApplicationVndSegmentV1alphaPlusJSONObject *CreateEdgeFunctions200ApplicationVndSegmentV1alphaPlusJSON
}
