// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

// CreateTrackingPlan200ApplicationVndSegmentV1betaPlusJSON - OK
type CreateTrackingPlan200ApplicationVndSegmentV1betaPlusJSON struct {
	// Result of a CreateTrackingPlan call.
	Data *shared.CreateTrackingPlanV1Output `json:"data,omitempty"`
}

// CreateTrackingPlan200ApplicationVndSegmentV1alphaPlusJSON - OK
type CreateTrackingPlan200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Result of a CreateTrackingPlan call.
	Data *shared.CreateTrackingPlanV1Output `json:"data,omitempty"`
}

// CreateTrackingPlan200ApplicationVndSegmentV1PlusJSON - OK
type CreateTrackingPlan200ApplicationVndSegmentV1PlusJSON struct {
	// Result of a CreateTrackingPlan call.
	Data *shared.CreateTrackingPlanV1Output `json:"data,omitempty"`
}

// CreateTrackingPlan200ApplicationJSON - OK
type CreateTrackingPlan200ApplicationJSON struct {
	// Result of a CreateTrackingPlan call.
	Data *shared.CreateTrackingPlanV1Output `json:"data,omitempty"`
}

type CreateTrackingPlanResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateTrackingPlan200ApplicationJSONObject *CreateTrackingPlan200ApplicationJSON
	// OK
	CreateTrackingPlan200ApplicationVndSegmentV1PlusJSONObject *CreateTrackingPlan200ApplicationVndSegmentV1PlusJSON
	// OK
	CreateTrackingPlan200ApplicationVndSegmentV1alphaPlusJSONObject *CreateTrackingPlan200ApplicationVndSegmentV1alphaPlusJSON
	// OK
	CreateTrackingPlan200ApplicationVndSegmentV1betaPlusJSONObject *CreateTrackingPlan200ApplicationVndSegmentV1betaPlusJSON
}
