// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

// CreateInvites200ApplicationVndSegmentV1betaPlusJSON - OK
type CreateInvites200ApplicationVndSegmentV1betaPlusJSON struct {
	// Returns the emails of the invited users.
	Data *shared.CreateInvitesV1Output `json:"data,omitempty"`
}

// CreateInvites200ApplicationVndSegmentV1alphaPlusJSON - OK
type CreateInvites200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Returns the emails of the invited users.
	Data *shared.CreateInvitesV1Output `json:"data,omitempty"`
}

// CreateInvites200ApplicationVndSegmentV1PlusJSON - OK
type CreateInvites200ApplicationVndSegmentV1PlusJSON struct {
	// Returns the emails of the invited users.
	Data *shared.CreateInvitesV1Output `json:"data,omitempty"`
}

// CreateInvites200ApplicationJSON - OK
type CreateInvites200ApplicationJSON struct {
	// Returns the emails of the invited users.
	Data *shared.CreateInvitesV1Output `json:"data,omitempty"`
}

type CreateInvitesResponse struct {
	ContentType string
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	StatusCode           int
	RawResponse          *http.Response
	// OK
	CreateInvites200ApplicationJSONObject *CreateInvites200ApplicationJSON
	// OK
	CreateInvites200ApplicationVndSegmentV1PlusJSONObject *CreateInvites200ApplicationVndSegmentV1PlusJSON
	// OK
	CreateInvites200ApplicationVndSegmentV1alphaPlusJSONObject *CreateInvites200ApplicationVndSegmentV1alphaPlusJSON
	// OK
	CreateInvites200ApplicationVndSegmentV1betaPlusJSONObject *CreateInvites200ApplicationVndSegmentV1betaPlusJSON
}
