// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type DeleteInsertFunctionInstanceRequest struct {
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceId"`
}

// DeleteInsertFunctionInstance200ApplicationVndSegmentV1alphaPlusJSON - OK
type DeleteInsertFunctionInstance200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Delete an insert Function instance.
	Data *shared.DeleteInsertFunctionInstanceAlphaOutput `json:"data,omitempty"`
}

type DeleteInsertFunctionInstanceResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// OK
	DeleteInsertFunctionInstance200ApplicationVndSegmentV1alphaPlusJSONObject *DeleteInsertFunctionInstance200ApplicationVndSegmentV1alphaPlusJSON
}
