// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type DeleteLabelRequest struct {
	Key   string `pathParam:"style=simple,explode=false,name=key"`
	Value string `pathParam:"style=simple,explode=false,name=value"`
}

// DeleteLabel200ApplicationVndSegmentV1betaPlusJSON - OK
type DeleteLabel200ApplicationVndSegmentV1betaPlusJSON struct {
	// Returns the status of a label deletion.
	Data *shared.DeleteLabelV1Output `json:"data,omitempty"`
}

// DeleteLabel200ApplicationVndSegmentV1alphaPlusJSON - OK
type DeleteLabel200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Returns the status of a label deletion.
	Data *shared.DeleteLabelAlphaOutput `json:"data,omitempty"`
}

// DeleteLabel200ApplicationVndSegmentV1PlusJSON - OK
type DeleteLabel200ApplicationVndSegmentV1PlusJSON struct {
	// Returns the status of a label deletion.
	Data *shared.DeleteLabelV1Output `json:"data,omitempty"`
}

// DeleteLabel200ApplicationJSON - OK
type DeleteLabel200ApplicationJSON struct {
	// Returns the status of a label deletion.
	Data *shared.DeleteLabelV1Output `json:"data,omitempty"`
}

type DeleteLabelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	DeleteLabel200ApplicationJSONObject *DeleteLabel200ApplicationJSON
	// OK
	DeleteLabel200ApplicationVndSegmentV1PlusJSONObject *DeleteLabel200ApplicationVndSegmentV1PlusJSON
	// OK
	DeleteLabel200ApplicationVndSegmentV1alphaPlusJSONObject *DeleteLabel200ApplicationVndSegmentV1alphaPlusJSON
	// OK
	DeleteLabel200ApplicationVndSegmentV1betaPlusJSONObject *DeleteLabel200ApplicationVndSegmentV1betaPlusJSON
}
