// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type GetLatestFromEdgeFunctionsRequest struct {
	SourceID string `pathParam:"style=simple,explode=false,name=sourceId"`
}

func (o *GetLatestFromEdgeFunctionsRequest) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

// GetLatestFromEdgeFunctionsResponseBody - OK
type GetLatestFromEdgeFunctionsResponseBody struct {
	// Output for GetLatestFromEdgeFunctions.
	Data *shared.GetLatestFromEdgeFunctionsAlphaOutput `json:"data,omitempty"`
}

func (o *GetLatestFromEdgeFunctionsResponseBody) GetData() *shared.GetLatestFromEdgeFunctionsAlphaOutput {
	if o == nil {
		return nil
	}
	return o.Data
}

type GetLatestFromEdgeFunctionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// OK
	Object *GetLatestFromEdgeFunctionsResponseBody
}

func (o *GetLatestFromEdgeFunctionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetLatestFromEdgeFunctionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetLatestFromEdgeFunctionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetLatestFromEdgeFunctionsResponse) GetRequestErrorEnvelope() *shared.RequestErrorEnvelope {
	if o == nil {
		return nil
	}
	return o.RequestErrorEnvelope
}

func (o *GetLatestFromEdgeFunctionsResponse) GetObject() *GetLatestFromEdgeFunctionsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
