// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type ListUsersRequest struct {
	// Pagination for users.
	//
	// This parameter exists in v1.
	Pagination shared.PaginationInput `queryParam:"style=deepObject,explode=true,name=pagination"`
}

// ListUsers200ApplicationVndSegmentV1betaPlusJSON - OK
type ListUsers200ApplicationVndSegmentV1betaPlusJSON struct {
	// Returns the list of users.
	Data *shared.ListUsersV1Output `json:"data,omitempty"`
}

// ListUsers200ApplicationVndSegmentV1alphaPlusJSON - OK
type ListUsers200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Returns the list of users.
	Data *shared.ListUsersV1Output `json:"data,omitempty"`
}

// ListUsers200ApplicationVndSegmentV1PlusJSON - OK
type ListUsers200ApplicationVndSegmentV1PlusJSON struct {
	// Returns the list of users.
	Data *shared.ListUsersV1Output `json:"data,omitempty"`
}

// ListUsers200ApplicationJSON - OK
type ListUsers200ApplicationJSON struct {
	// Returns the list of users.
	Data *shared.ListUsersV1Output `json:"data,omitempty"`
}

type ListUsersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListUsers200ApplicationJSONObject *ListUsers200ApplicationJSON
	// OK
	ListUsers200ApplicationVndSegmentV1PlusJSONObject *ListUsers200ApplicationVndSegmentV1PlusJSON
	// OK
	ListUsers200ApplicationVndSegmentV1alphaPlusJSONObject *ListUsers200ApplicationVndSegmentV1alphaPlusJSON
	// OK
	ListUsers200ApplicationVndSegmentV1betaPlusJSONObject *ListUsers200ApplicationVndSegmentV1betaPlusJSON
}
