// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type ListSchemaSettingsInSourceRequest struct {
	SourceID string `pathParam:"style=simple,explode=false,name=sourceId"`
}

// ListSchemaSettingsInSource200ApplicationVndSegmentV1betaPlusJSON - OK
type ListSchemaSettingsInSource200ApplicationVndSegmentV1betaPlusJSON struct {
	// Returns a list of settings for the Source.
	Data *shared.ListSchemaSettingsInSourceV1Output `json:"data,omitempty"`
}

// ListSchemaSettingsInSource200ApplicationVndSegmentV1alphaPlusJSON - OK
type ListSchemaSettingsInSource200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Returns a list of settings for the Source.
	Data *shared.ListSchemaSettingsInSourceV1Output `json:"data,omitempty"`
}

// ListSchemaSettingsInSource200ApplicationVndSegmentV1PlusJSON - OK
type ListSchemaSettingsInSource200ApplicationVndSegmentV1PlusJSON struct {
	// Returns a list of settings for the Source.
	Data *shared.ListSchemaSettingsInSourceV1Output `json:"data,omitempty"`
}

// ListSchemaSettingsInSource200ApplicationJSON - OK
type ListSchemaSettingsInSource200ApplicationJSON struct {
	// Returns a list of settings for the Source.
	Data *shared.ListSchemaSettingsInSourceV1Output `json:"data,omitempty"`
}

type ListSchemaSettingsInSourceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ListSchemaSettingsInSource200ApplicationJSONObject *ListSchemaSettingsInSource200ApplicationJSON
	// OK
	ListSchemaSettingsInSource200ApplicationVndSegmentV1PlusJSONObject *ListSchemaSettingsInSource200ApplicationVndSegmentV1PlusJSON
	// OK
	ListSchemaSettingsInSource200ApplicationVndSegmentV1alphaPlusJSONObject *ListSchemaSettingsInSource200ApplicationVndSegmentV1alphaPlusJSON
	// OK
	ListSchemaSettingsInSource200ApplicationVndSegmentV1betaPlusJSONObject *ListSchemaSettingsInSource200ApplicationVndSegmentV1betaPlusJSON
}
