// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type RemoveAudienceFromSpaceRequest struct {
	ID      string `pathParam:"style=simple,explode=false,name=id"`
	SpaceID string `pathParam:"style=simple,explode=false,name=spaceId"`
}

// RemoveAudienceFromSpace200ApplicationVndSegmentV1alphaPlusJSON - OK
type RemoveAudienceFromSpace200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Delete audience endpoint output.
	Data *shared.RemoveAudienceFromSpaceAlphaOutput `json:"data,omitempty"`
}

type RemoveAudienceFromSpaceResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// OK
	RemoveAudienceFromSpace200ApplicationVndSegmentV1alphaPlusJSONObject *RemoveAudienceFromSpace200ApplicationVndSegmentV1alphaPlusJSON
}
