// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type RemoveSubscriptionFromDestinationRequest struct {
	DestinationID string `pathParam:"style=simple,explode=false,name=destinationId"`
	ID            string `pathParam:"style=simple,explode=false,name=id"`
}

// RemoveSubscriptionFromDestination200ApplicationVndSegmentV1alphaPlusJSON - OK
type RemoveSubscriptionFromDestination200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Returns a Destination deletion flag.
	Data *shared.RemoveSubscriptionFromDestinationAlphaOutput `json:"data,omitempty"`
}

type RemoveSubscriptionFromDestinationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// OK
	RemoveSubscriptionFromDestination200ApplicationVndSegmentV1alphaPlusJSONObject *RemoveSubscriptionFromDestination200ApplicationVndSegmentV1alphaPlusJSON
}
