// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type ReplaceUsersInUserGroupRequest struct {
	ReplaceUsersInUserGroupV1Input shared.ReplaceUsersInUserGroupV1Input `request:"mediaType=application/vnd.segment.v1beta+json"`
	UserGroupID                    string                                `pathParam:"style=simple,explode=false,name=userGroupId"`
}

func (o *ReplaceUsersInUserGroupRequest) GetReplaceUsersInUserGroupV1Input() shared.ReplaceUsersInUserGroupV1Input {
	if o == nil {
		return shared.ReplaceUsersInUserGroupV1Input{}
	}
	return o.ReplaceUsersInUserGroupV1Input
}

func (o *ReplaceUsersInUserGroupRequest) GetUserGroupID() string {
	if o == nil {
		return ""
	}
	return o.UserGroupID
}

// ReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSON - OK
type ReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSON struct {
	// Returns the updated user group.
	Data *shared.ReplaceUsersInUserGroupV1Output `json:"data,omitempty"`
}

func (o *ReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSON) GetData() *shared.ReplaceUsersInUserGroupV1Output {
	if o == nil {
		return nil
	}
	return o.Data
}

// ReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSON - OK
type ReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Returns the updated user group.
	Data *shared.ReplaceUsersInUserGroupV1Output `json:"data,omitempty"`
}

func (o *ReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSON) GetData() *shared.ReplaceUsersInUserGroupV1Output {
	if o == nil {
		return nil
	}
	return o.Data
}

// ReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSON - OK
type ReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSON struct {
	// Returns the updated user group.
	Data *shared.ReplaceUsersInUserGroupV1Output `json:"data,omitempty"`
}

func (o *ReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSON) GetData() *shared.ReplaceUsersInUserGroupV1Output {
	if o == nil {
		return nil
	}
	return o.Data
}

// ReplaceUsersInUserGroup200ApplicationJSON - OK
type ReplaceUsersInUserGroup200ApplicationJSON struct {
	// Returns the updated user group.
	Data *shared.ReplaceUsersInUserGroupV1Output `json:"data,omitempty"`
}

func (o *ReplaceUsersInUserGroup200ApplicationJSON) GetData() *shared.ReplaceUsersInUserGroupV1Output {
	if o == nil {
		return nil
	}
	return o.Data
}

type ReplaceUsersInUserGroupResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ReplaceUsersInUserGroup200ApplicationJSONObject *ReplaceUsersInUserGroup200ApplicationJSON
	// OK
	ReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSONObject *ReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSON
	// OK
	ReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSONObject *ReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSON
	// OK
	ReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSONObject *ReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSON
}

func (o *ReplaceUsersInUserGroupResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReplaceUsersInUserGroupResponse) GetRequestErrorEnvelope() *shared.RequestErrorEnvelope {
	if o == nil {
		return nil
	}
	return o.RequestErrorEnvelope
}

func (o *ReplaceUsersInUserGroupResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReplaceUsersInUserGroupResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ReplaceUsersInUserGroupResponse) GetReplaceUsersInUserGroup200ApplicationJSONObject() *ReplaceUsersInUserGroup200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.ReplaceUsersInUserGroup200ApplicationJSONObject
}

func (o *ReplaceUsersInUserGroupResponse) GetReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSONObject() *ReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSON {
	if o == nil {
		return nil
	}
	return o.ReplaceUsersInUserGroup200ApplicationVndSegmentV1PlusJSONObject
}

func (o *ReplaceUsersInUserGroupResponse) GetReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSONObject() *ReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSON {
	if o == nil {
		return nil
	}
	return o.ReplaceUsersInUserGroup200ApplicationVndSegmentV1alphaPlusJSONObject
}

func (o *ReplaceUsersInUserGroupResponse) GetReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSONObject() *ReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSON {
	if o == nil {
		return nil
	}
	return o.ReplaceUsersInUserGroup200ApplicationVndSegmentV1betaPlusJSONObject
}
