// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"segment_public_api/internal/sdk/pkg/models/shared"
)

type UpdateDestinationRequest struct {
	UpdateDestinationV1Input shared.UpdateDestinationV1Input `request:"mediaType=application/vnd.segment.v1beta+json"`
	DestinationID            string                          `pathParam:"style=simple,explode=false,name=destinationId"`
}

// UpdateDestination200ApplicationVndSegmentV1betaPlusJSON - OK
type UpdateDestination200ApplicationVndSegmentV1betaPlusJSON struct {
	// Returns the updated Destination.
	Data *shared.UpdateDestinationV1Output `json:"data,omitempty"`
}

// UpdateDestination200ApplicationVndSegmentV1alphaPlusJSON - OK
type UpdateDestination200ApplicationVndSegmentV1alphaPlusJSON struct {
	// Returns the updated Destination.
	Data *shared.UpdateDestinationV1Output `json:"data,omitempty"`
}

// UpdateDestination200ApplicationVndSegmentV1PlusJSON - OK
type UpdateDestination200ApplicationVndSegmentV1PlusJSON struct {
	// Returns the updated Destination.
	Data *shared.UpdateDestinationV1Output `json:"data,omitempty"`
}

// UpdateDestination200ApplicationJSON - OK
type UpdateDestination200ApplicationJSON struct {
	// Returns the updated Destination.
	Data *shared.UpdateDestinationV1Output `json:"data,omitempty"`
}

type UpdateDestinationResponse struct {
	ContentType string
	// Resource not found
	RequestErrorEnvelope *shared.RequestErrorEnvelope
	StatusCode           int
	RawResponse          *http.Response
	// OK
	UpdateDestination200ApplicationJSONObject *UpdateDestination200ApplicationJSON
	// OK
	UpdateDestination200ApplicationVndSegmentV1PlusJSONObject *UpdateDestination200ApplicationVndSegmentV1PlusJSON
	// OK
	UpdateDestination200ApplicationVndSegmentV1alphaPlusJSONObject *UpdateDestination200ApplicationVndSegmentV1alphaPlusJSON
	// OK
	UpdateDestination200ApplicationVndSegmentV1betaPlusJSONObject *UpdateDestination200ApplicationVndSegmentV1betaPlusJSON
}
